import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Character, GetCharacterResults } from '../types'
import Login2 from './Login2'
import Login3 from './Login3'
import Login4 from './Login4'
import Responsive from './Responsive'

const Home: NextPage<{characters: Character[]}> = ({ characters }: any) => {
  
  return (
    <div>
      <Head>
        <title>My APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Login4/>
      </main>
    </div>
  )
}

export default Home



export const getStaticProps: GetStaticProps = async (context) => {

  const res = await fetch(`https://rickandmortyapi.com/api/character`);

  const { results }: GetCharacterResults = await res.json();

  return {
    props: {
      characters: results, 
    }
  }

}