import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Character, GetCharacterResults } from '../types'

const Home: NextPage<{characters: Character[]}> = ({ characters }: any) => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>HELL WORLD</h1>
        {characters.map((character: any) => {
           return <div key={character.id}>
          <Link href={`/characters/${character.id}`}>
          <h1>{character.name}</h1>
          </Link>   
           
           <Image 
           src={character.image}            
           alt={character.name}
           width="200"
           height="200"
           />
           </div> 
        })}
      </main>
    </div>
  )
}

export default Home



export const getStaticProps: GetStaticProps = async (context) => {

  const res = await fetch(`https://rickandmortyapi.com/api/character`);

  const { results }: GetCharacterResults = await res.json();

  return {
    props: {
      characters: results, 
    }
  }

}